import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class AnalyticsPDFService {
  static Future<String> generateAnalyticsReport({
    required double totalCollectedRevenue,
    required double projectedRevenue,
    required double outstandingRent,
    required int activeTenantsCount,
    required int expiringLeasesCount,
    required int totalProperties,
    required int totalUnits,
    required String occupancyRate,
    required int vacantUnits,
    required int openRequests,
    required int completedRequests,
  }) async {
    final pdf = pw.Document();
    final currency = NumberFormat.currency(symbol: 'KES ', decimalDigits: 0);
    final now = DateTime.now();
    final dateStr = DateFormat('MMM d, yyyy').format(now);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Landlord Analytics Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.Text(dateStr, style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          
          // Financials
          _buildSectionTitle('Financial Overview'),
          _buildMetricRow('Total Revenue Collected', currency.format(totalCollectedRevenue), PdfColors.green700),
          _buildMetricRow('Projected Monthly Revenue', currency.format(projectedRevenue)),
          _buildMetricRow('Outstanding Rent', currency.format(outstandingRent), outstandingRent > 0 ? PdfColors.orange700 : PdfColors.black),
          pw.SizedBox(height: 10),
          pw.Divider(),
          
          // Lease & Tenants
          _buildSectionTitle('Lease & Tenant Health'),
          _buildMetricRow('Active Tenants', activeTenantsCount.toString()),
          _buildMetricRow('Leases Expiring Soon (60 Days)', expiringLeasesCount.toString(), expiringLeasesCount > 0 ? PdfColors.red700 : PdfColors.black),
          pw.SizedBox(height: 10),
          pw.Divider(),

          // Portfolio
          _buildSectionTitle('Portfolio Statistics'),
          pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _buildStatBox('Properties', totalProperties.toString()),
                _buildStatBox('Total Units', totalUnits.toString()),
                _buildStatBox('Occupancy', '$occupancyRate%'),
                _buildStatBox('Vacant', vacantUnits.toString()),
              ]
          ),
          pw.SizedBox(height: 20),

          // Maintenance
          _buildSectionTitle('Maintenance Summary'),
          pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.start,
              children: [
                _buildStatBox('Open Requests', openRequests.toString(), color: PdfColors.red700),
                pw.SizedBox(width: 20),
                _buildStatBox('Completed', completedRequests.toString(), color: PdfColors.green700),
              ]
          ),

          pw.Spacer(),
          pw.Center(
            child: pw.Text('Generated by Chak Property System', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
          ),
        ],
      ),
    );

    final bytes = await pdf.save();
    final fileName = 'analytics_report_${DateFormat('yyyyMMdd_HHmm').format(now)}';

    // 1. Open in Native Print/PDF Viewer (Allows Viewing & Saving)
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => bytes,
      name: fileName,
    );
    
    // 2. Also save to local documents for persistence (optional backup)
    try {
      final dir = await getApplicationDocumentsDirectory();
      final file = File('${dir.path}/$fileName.pdf');
      await file.writeAsBytes(bytes);
      return file.path;
    } catch (e) {
      return '';
    }
  }

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 10),
      child: pw.Text(
        title,
        style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800),
      ),
    );
  }

  static pw.Widget _buildMetricRow(String label, String value, [PdfColor color = PdfColors.black]) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 14)),
          pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: color)),
        ],
      ),
    );
  }

  static pw.Widget _buildStatBox(String label, String value, {PdfColor color = PdfColors.black}) {
    return pw.Expanded(
      child: pw.Container(
        margin: const pw.EdgeInsets.symmetric(horizontal: 4),
        padding: const pw.EdgeInsets.all(10),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: PdfColors.grey400),
          borderRadius: pw.BorderRadius.circular(4),
        ),
        child: pw.Column(
          children: [
            pw.Text(value, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: color)),
            pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600), textAlign: pw.TextAlign.center),
          ],
        ),
      ),
    );
  }
}
